INSERT INTO goods (name, price, number) VALUES ("Банка с крышкой большая", 5839, 1);
INSERT INTO goods (name, price, number) VALUES ("Банка с крышкой малая", 8859, 2);
INSERT INTO goods (name, price, number) VALUES ("Блюдце", 3999, 3);
INSERT INTO goods (name, price, number) VALUES ("Блюдце квадратное", 920, 4);
INSERT INTO goods (name, price, number) VALUES ("Блюдце кофейное", 4176, 5);
INSERT INTO goods (name, price, number) VALUES ("Блюдце чайное ", 5278, 6);
INSERT INTO goods (name, price, number) VALUES ("Бокал", 5436, 7);
INSERT INTO goods (name, price, number) VALUES ("Бокал Червленый", 1850, 8);
INSERT INTO goods (name, price, number) VALUES ("Бочонок", 6996, 9);
INSERT INTO goods (name, price, number) VALUES ("Бочонок для лука", 7108, 10);
INSERT INTO goods (name, price, number) VALUES ("Бочонок малый", 9267, 11);
INSERT INTO goods (name, price, number) VALUES ("Ваза напольная", 1701, 12);
INSERT INTO goods (name, price, number) VALUES ("Ваза Червленая", 713, 13);
INSERT INTO goods (name, price, number) VALUES ("Вазочка сувенирная", 3100, 14);
INSERT INTO goods (name, price, number) VALUES ("Гляк большой", 3553, 15);
INSERT INTO goods (name, price, number) VALUES ("Гляк малый", 4732, 16);
INSERT INTO goods (name, price, number) VALUES ("Гномик с бочкой", 6734, 17);
INSERT INTO goods (name, price, number) VALUES ("Горчичница", 4763, 18);
INSERT INTO goods (name, price, number) VALUES ("Горшок большой", 2586, 19);
INSERT INTO goods (name, price, number) VALUES ("Горшок для творога", 8860, 20);
INSERT INTO goods (name, price, number) VALUES ("Горшок широкий без крышки", 2584, 21);
INSERT INTO goods (name, price, number) VALUES ("Горшочек ", 247, 22);
INSERT INTO goods (name, price, number) VALUES ("Горшочек большой от пельменного набора", 7607, 23);
INSERT INTO goods (name, price, number) VALUES ("Горшочек для мёда малый", 4464, 24);
INSERT INTO goods (name, price, number) VALUES ("Горшочек малый от пельменного набора", 8169, 25);
INSERT INTO goods (name, price, number) VALUES ("Горшочек на стену", 3093, 26);
INSERT INTO goods (name, price, number) VALUES ("Горшочек низкий", 142, 27);
INSERT INTO goods (name, price, number) VALUES ("Горшочек порционный", 8214, 28);
INSERT INTO goods (name, price, number) VALUES ("Горшочек с россписью большой", 6039, 29);
INSERT INTO goods (name, price, number) VALUES ("Горшочек с россписью малый", 1854, 30);
INSERT INTO goods (name, price, number) VALUES ("Горшочек с россписью средний", 1699, 31);
INSERT INTO goods (name, price, number) VALUES ("Горшочек с ручками", 4450, 32);
INSERT INTO goods (name, price, number) VALUES ("Горшочек средний", 5829, 33);
INSERT INTO goods (name, price, number) VALUES ("Гошочек для меда большой", 4645, 34);
INSERT INTO goods (name, price, number) VALUES ("Дисертница", 8681, 35);
INSERT INTO goods (name, price, number) VALUES ("Жаровница", 9406, 36);
INSERT INTO goods (name, price, number) VALUES ("Жульенница", 5714, 37);
INSERT INTO goods (name, price, number) VALUES ("Икорница", 5403, 38);
INSERT INTO goods (name, price, number) VALUES ("Кабан", 4008, 39);
INSERT INTO goods (name, price, number) VALUES ("Кашник", 416, 40);
INSERT INTO goods (name, price, number) VALUES ("Кашпо", 3237, 41);
INSERT INTO goods (name, price, number) VALUES ("Кокотница", 2698, 42);
INSERT INTO goods (name, price, number) VALUES ("Колокольчик малый", 1565, 43);
INSERT INTO goods (name, price, number) VALUES ("Комплект кружек", 1878, 44);
INSERT INTO goods (name, price, number) VALUES ("Конфетница", 5484, 45);
INSERT INTO goods (name, price, number) VALUES ("Копилка", 3646, 46);
INSERT INTO goods (name, price, number) VALUES ("Кофейник", 7486, 47);
INSERT INTO goods (name, price, number) VALUES ("Кружка", 7170, 48);
INSERT INTO goods (name, price, number) VALUES ("Крынка большая", 4020, 49);
INSERT INTO goods (name, price, number) VALUES ("Крынка малая", 4286, 50);
INSERT INTO goods (name, price, number) VALUES ("Крынка с росписью", 4417, 51);
INSERT INTO goods (name, price, number) VALUES ("Крынка с ручками", 5002, 52);
INSERT INTO goods (name, price, number) VALUES ("Крынка средняя", 3410, 53);
INSERT INTO goods (name, price, number) VALUES ("Крынка сувенирная", 7912, 54);
INSERT INTO goods (name, price, number) VALUES ("Кубок", 4180, 55);
INSERT INTO goods (name, price, number) VALUES ("Кубок малый", 5183, 56);
INSERT INTO goods (name, price, number) VALUES ("Кубок со звоном", 7397, 57);
INSERT INTO goods (name, price, number) VALUES ("Кубок средний", 6449, 58);
INSERT INTO goods (name, price, number) VALUES ("Кувшин", 8165, 59);
INSERT INTO goods (name, price, number) VALUES ("Кувшин большой", 1843, 60);
INSERT INTO goods (name, price, number) VALUES ("Кувшин для вина большой", 3132, 61);
INSERT INTO goods (name, price, number) VALUES ("Кувшин для вина средний", 9172, 62);
INSERT INTO goods (name, price, number) VALUES ("Кувшин для молока", 7821, 63);
INSERT INTO goods (name, price, number) VALUES ("Кувшин для напитков", 7449, 64);
INSERT INTO goods (name, price, number) VALUES ("Кувшин малый", 9113, 65);
INSERT INTO goods (name, price, number) VALUES ("Кувшин с росписью", 2743, 66);
INSERT INTO goods (name, price, number) VALUES ("Кувшин средний", 3811, 67);
INSERT INTO goods (name, price, number) VALUES ("Кувшин сувенирный", 3090, 68);
INSERT INTO goods (name, price, number) VALUES ("Кувшинчик сувенирный", 4991, 69);
INSERT INTO goods (name, price, number) VALUES ("Курочка под яйцо", 6741, 70);
INSERT INTO goods (name, price, number) VALUES ("Масленка", 7834, 71);
INSERT INTO goods (name, price, number) VALUES ("Медовница большая", 5630, 72);
INSERT INTO goods (name, price, number) VALUES ("Медовница малая", 3152, 73);
INSERT INTO goods (name, price, number) VALUES ("Менажница", 7177, 74);
INSERT INTO goods (name, price, number) VALUES ("Менажница маля", 6341, 75);
INSERT INTO goods (name, price, number) VALUES ("Менажница с рописью", 164, 76);
INSERT INTO goods (name, price, number) VALUES ("Миска большая", 270, 77);
INSERT INTO goods (name, price, number) VALUES ("Миска большая червленая", 4799, 78);
INSERT INTO goods (name, price, number) VALUES ("Миска малая", 8100, 79);
INSERT INTO goods (name, price, number) VALUES ("Миска средняя", 3297, 80);
INSERT INTO goods (name, price, number) VALUES ("Миска средняя червленая", 7884, 81);
INSERT INTO goods (name, price, number) VALUES ("Молочник", 5761, 82);
INSERT INTO goods (name, price, number) VALUES ("Набор банок", 4861, 83);
INSERT INTO goods (name, price, number) VALUES ("Набор для молока", 4244, 84);
INSERT INTO goods (name, price, number) VALUES ("Набор для напитков", 1013, 85);
INSERT INTO goods (name, price, number) VALUES ("Набор для окрошки", 5088, 86);
INSERT INTO goods (name, price, number) VALUES ("Набор для пельменей", 5447, 87);
INSERT INTO goods (name, price, number) VALUES ("Набор чайников для заварки", 3248, 88);
INSERT INTO goods (name, price, number) VALUES ("Опарник средний", 2704, 89);
INSERT INTO goods (name, price, number) VALUES ("Панно", 1601, 90);
INSERT INTO goods (name, price, number) VALUES ("Пельменница", 2273, 91);
INSERT INTO goods (name, price, number) VALUES ("Пельменница большая", 988, 92);
INSERT INTO goods (name, price, number) VALUES ("Пепельница", 6085, 93);
INSERT INTO goods (name, price, number) VALUES ("Пиала", 41, 94);
INSERT INTO goods (name, price, number) VALUES ("Пиала червленая", 6130, 95);
INSERT INTO goods (name, price, number) VALUES ("Плошка", 5354, 96);